// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cs_scale
List cs_scale(arma::mat X);
RcppExport SEXP _SelectBoost_gamlss_cs_scale(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cs_scale(X));
    return rcpp_result_gen;
END_RCPP
}
// cs_cor
arma::mat cs_cor(const arma::mat& X);
RcppExport SEXP _SelectBoost_gamlss_cs_cor(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cs_cor(X));
    return rcpp_result_gen;
END_RCPP
}
// pos_trapz_norm
double pos_trapz_norm(const arma::vec& c0, const arma::vec& prop, double thr);
RcppExport SEXP _SelectBoost_gamlss_pos_trapz_norm(SEXP c0SEXP, SEXP propSEXP, SEXP thrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prop(propSEXP);
    Rcpp::traits::input_parameter< double >::type thr(thrSEXP);
    rcpp_result_gen = Rcpp::wrap(pos_trapz_norm(c0, prop, thr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SelectBoost_gamlss_cs_scale", (DL_FUNC) &_SelectBoost_gamlss_cs_scale, 1},
    {"_SelectBoost_gamlss_cs_cor", (DL_FUNC) &_SelectBoost_gamlss_cs_cor, 1},
    {"_SelectBoost_gamlss_pos_trapz_norm", (DL_FUNC) &_SelectBoost_gamlss_pos_trapz_norm, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SelectBoost_gamlss(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
