# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cs_scale <- function(X) {
    .Call(`_SelectBoost_gamlss_cs_scale`, X)
}

cs_cor <- function(X) {
    .Call(`_SelectBoost_gamlss_cs_cor`, X)
}

pos_trapz_norm <- function(c0, prop, thr) {
    .Call(`_SelectBoost_gamlss_pos_trapz_norm`, c0, prop, thr)
}

